### ISSUE TITLE
Upgrade django version to 3.2 LTS

### ISSUE THREAD

**Issue by rafaelreuber** [app-generator/django-dashboard-argon#3]
Django released the 3.2 LTS on April 6 would be nice upgrade for this version instead use 2x version.

**Comment by app-generator** [comment]
Hello @rafaelreuber,

Thank you for your suggestion. All Django starters will be updated soon. 

Let us know if we can improve anything else.

*AppSeed Support*

**Comment by app-generator** [comment]
Hello @rafaelreuber, 

The codebase has been updated to **3.2.6**. 

Closing

P.S. In case you have the time, here is the link to the product ROADMAP: 

https://github.com/app-generator/boilerplate-code-django-dashboard/issues/14
